apiVersion: apps/v1
kind: Deployement
metadata:
  name: java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels: 
        app: java-app
    spec:
      containers:
      - name: java-app
        image: harsha6798/java-app-ci-image:replaceImageTag
        ports:
        - containerPort: 8080


